[signer_pool]
# Selection strategy: round_robin, random, weighted
strategy = "round_robin"

[[signers]]
name = "mainnet_fee_payer"
type = "memory"
private_key_env = "KORA_MAINNET_PRIVATE_KEY"
weight = 1

